[project]
name = "email-reputation-tool-ck"
version = "0.1.0"
description = "Email Reputation Tool contains all the boilerplate you need to create the package of the tool"
readme = "README.md"
authors = [
  {name = "Diego Favaro", email = "diego.favaro@kraken.tech"}
]
maintainers = [
  {name = "Diego Favaro", email = "diego.favaro@kraken.tech"}
]
classifiers = [

]
license = {text = "MIT"}
dependencies = [
  "typer"
]
requires-python = ">= 3.10"

[project.optional-dependencies]
test = [
    "coverage",  # testing
    "pytest",  # testing
    "ruff",  # linting
    "ty", # checking types
    "ipdb"    
]

[project.urls]
bugs = "https://github.com/Furtivo360/email_reputation_tool_ck/issues"
changelog = "https://github.com/Furtivo360/email_reputation_tool_ck/blob/master/changelog.md"
homepage = "https://github.com/Furtivo360/email_reputation_tool_ck"

[project.scripts]
email_reputation_tool_ck = "email_reputation_tool_ck.cli:app"

[tool.ty]
# All rules are enabled as "error" by default; no need to specify unless overriding.
# Example override: relax a rule for the entire project (uncomment if needed).
# rules.TY015 = "warn"  # For invalid-argument-type, warn instead of error.

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
]

[tool.uv]
package = true
